# Generated by Django 5.0.4 on 2024-05-20 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_passwordreset_delete_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordreset',
            name='user',
        ),
    ]
