name: CI

on:
  pull_request:
    branchs: ["master"]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: install requerments
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/requirements.txt
