# Generated by Django 5.0.4 on 2024-04-28 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_studentactivity_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentactivity',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
