# Generated by Django 5.0.4 on 2024-05-07 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_exam_examscore'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='competence_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.competencelevel'),
        ),
        migrations.AlterField(
            model_name='examscore',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.exam'),
        ),
        migrations.AlterField(
            model_name='examscore',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student'),
        ),
    ]
