# Generated by Django 5.0.4 on 2024-05-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
      ('activities', '0003_rename_lecture_lectureattendance_lecture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentactivity',
            name='score_image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentactivity',
            name='score_image_2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
