# Generated by Django 5.0.4 on 2024-05-19 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_rename_lecture_lectureattendance_lecture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentactivity',
            name='image2_path',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentactivity',
            name='image_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
