# Generated by Django 5.0.4 on 2024-05-19 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_studentactivity_image2_path_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentactivity',
            old_name='image2_path',
            new_name='score_image',
        ),
        migrations.RenameField(
            model_name='studentactivity',
            old_name='image_path',
            new_name='score_image_2',
        ),
    ]
