# Generated by Django 5.0.4 on 2024-04-28 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentNotification',
            new_name='ActivityNotification',
        ),
    ]
