name: CI

on:
  pull_request:
    branchs: ["master", "dev"]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: install requerments
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/requirements.txt
        pip install -r requirements/test_requirements.txt
    - name: run flake8
      run: flake8
    - name: isort
      run: isort . --check --diff
    - name: run tests
      run: |
        python manage.py test
